### ISSUE TITLE
iambic import does not update access rules correctly when local identity center files already exists

### ISSUE THREAD

**Issue by dushyantbhardwaj9** [noqdev/iambic-templates-examples#21]
I did `iambic import` and it brought all the resources in the local directory. After a couple of updates permission sets and mapping to users(not through iambic). When I ran `iambic import` again, it did not bring all changes to the file. My guess is it did not write the new changes to the files.

**Comment by smoy** [comment]
ah, this issue should be move to noqdev/iambic, and its handled by https://github.com/noqdev/iambic/pull/604
